---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chatbot-1730723149321
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-1730723149321 
  name: chatbot-1730723149321
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi